### ISSUE TITLE
[BUG] Unable to import in Anaconda 3 on macOS

### ISSUE THREAD

**Issue by nelsonyao111** [PreferredAI/cornac#360]
### Description
I was trying to run `import cornac` in a jupyter notebook under an anaconda environment, but an error was returned.

### In which platform does it happen?

I am running on macOS Catalina 10.15.5. My jupyter notebook was running on Anaconda 3. The environment I was running on has the following package:
```appnope                   0.1.0                    pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
ca-certificates           2020.7.22                     0  
certifi                   2020.6.20                py37_0  
cornac                    1.7.1                    pypi_0    pypi
decorator                 4.4.2                    pypi_0    pypi
ipykernel                 5.3.4                    pypi_0    pypi
ipython                   7.18.1                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
jedi                      0.17.2                   pypi_0    pypi
jupyter-client            6.1.7                    pypi_0    pypi
jupyter-core              4.6.3                    pypi_0    pypi
libcxx                    10.0.0                        1  
libedit                   3.1.20191231         h1de35cc_1  
libffi                    3.3                  hb1e8313_2  
ncurses                   6.2                  h0a44026_1  
numpy                     1.19.2                   pypi_0    pypi
openssl                   1.1.1h               haf1e3a3_0  
parso                     0.7.1                    pypi_0    pypi
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pip                       20.2.2                   py37_0  
prompt-toolkit            3.0.7                    pypi_0    pypi
ptyprocess                0.6.0                    pypi_0    pypi
pygments                  2.7.1                    pypi_0    pypi
python                    3.7.9                h26836e1_0  
python-dateutil           2.8.1                    pypi_0    pypi
pyzmq                     19.0.2                   pypi_0    pypi
readline                  8.0                  h1de35cc_0  
scipy                     1.5.2                    pypi_0    pypi
setuptools                49.6.0                   py37_1  
six                       1.15.0                   pypi_0    pypi
sqlite                    3.33.0               hffcf06c_0  
tk                        8.6.10               hb0a8c7a_0  
tornado                   6.0.4                    pypi_0    pypi
tqdm                      4.50.0                   pypi_0    pypi
traitlets                 5.0.4                    pypi_0    pypi
wcwidth                   0.2.5                    pypi_0    pypi
wheel                     0.35.1                     py_0  
xz                        5.2.5                h1de35cc_0  
zlib                      1.2.11               h1de35cc_3  
```

### How do we replicate the issue?
Run: 
```
conda create --name new_env python=3.7 
conda activate new_env
pip install cornac
```
Under the `new_env` environment, open a python shell and run 
``` import cornac```
An error message is returned: 
```>>> import cornac
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/envs/new_env/lib/python3.7/site-packages/cornac/__init__.py", line 16, in <module>
    from . import data
  File "/opt/anaconda3/envs/new_env/lib/python3.7/site-packages/cornac/data/__init__.py", line 18, in <module>
    from .text import TextModality, ReviewModality
  File "/opt/anaconda3/envs/new_env/lib/python3.7/site-packages/cornac/data/text.py", line 27, in <module>
    from ..utils import normalize
  File "/opt/anaconda3/envs/new_env/lib/python3.7/site-packages/cornac/utils/__init__.py", line 20, in <module>
    from .fast_dot import fast_dot
ImportError: dlopen(/opt/anaconda3/envs/new_env/lib/python3.7/site-packages/cornac/utils/fast_dot.cpython-37m-darwin.so, 2): Library not loaded: /usr/local/opt/gcc/lib/gcc/9/libgomp.1.dylib
  Referenced from: /opt/anaconda3/envs/new_env/lib/python3.7/site-packages/cornac/utils/fast_dot.cpython-37m-darwin.so
  Reason: image not found
```

### Expected behavior (i.e. solution)

The import statement should run without error

**Comment by tqtg** [comment]
@nelsonyao111 it seems that you don't have `openmp` installed in your system. Please try to install `gcc` using `homebrew` as mentioned [here](https://github.com/PreferredAI/cornac#installation).
