### ISSUE TITLE
[ASK] ValueError: could not convert string to float: 'e

### ISSUE THREAD

**Issue by yasdel** [PreferredAI/cornac#398]
### Description
Hello,

I am trying to use cornac with [BookCrossing dataset.](https://grouplens.org/datasets/book-crossing/) I am facing a strong issue which I did not have with other datasets. 

```
hyperParam = 15
ds_name = 'BKcross'

path_to_samples = '/home/yas/PycharmProjects/cornac/datasets/BookCrossing/samples/*.csv'
load_ds_addr = '/home/yas/PycharmProjects/cornac/datasets/BookCrossing/BX-Book-Ratings.csv'
save_res_addr = '/home/yas/PycharmProjects/cornac/results/resultsUserLevel_'
save_feat_addr = '/home/yas/PycharmProjects/cornac/results/features_'
simple_headers = ["UserId","ItemId","Rating"]

userData_df = pd.read_csv(load_ds_addr, sep=';', skiprows=0)
userData_df.columns = simple_headers

print(userData_df.head())
print(userData_df.shape)

ratio_split = RatioSplit(data=userData_df, test_size=0.2, rating_threshold=4.0, exclude_unknowns=False, seed=123)
mf = cornac.models.MF(k=hyperParam, max_iter=25, learning_rate=0.01, lambda_reg=0.02, use_bias=True, seed=123)
ndcg_100 = cornac.metrics.NDCG(k=100)

```
The error I get is the following:

```

   UserId      ItemId  Rating
0  276725  034545104X       0
1  276726  0155061224       5
2  276727  0446520802       0
3  276729  052165615X       3
4  276729  0521795028       6
(1149780, 3)
Traceback (most recent call last):
  File "/home/yas/PycharmProjects/cornac/yd/main_BookCrossing.py", line 52, in <module>
    ratio_split = RatioSplit(data=userData_df, test_size=0.2, rating_threshold=4.0, exclude_unknowns=False, seed=123)
  File "/home/yas/PycharmProjects/cornac/cornac/eval_methods/ratio_split.py", line 61, in __init__
    self._split()
  File "/home/yas/PycharmProjects/cornac/cornac/eval_methods/ratio_split.py", line 105, in _split
    self.build(train_data=train_data, test_data=test_data, val_data=val_data)
  File "/home/yas/PycharmProjects/cornac/cornac/eval_methods/base_method.py", line 584, in build
    self._build_datasets(train_data, test_data, val_data)
  File "/home/yas/PycharmProjects/cornac/cornac/eval_methods/base_method.py", line 462, in _build_datasets
    self.train_set = Dataset.build(
  File "/home/yas/PycharmProjects/cornac/cornac/data/dataset.py", line 357, in build
    r_values.append(float(rating))
ValueError: could not convert string to float: 'e'
<!--- Describe your general ask in detail -->

```
It seems the error, is mentioning in the column Rating, there is a non-integer value. I however, could not verify that column Rating has a non-integer value. Any idea why the problem occurs and how it could be resolved? thank you

**Comment by tqtg** [comment]
@yasdel RatioSplit can not directly take in a pandas DataFrame, you can try to replace with the line below:
```python
ratio_split = RatioSplit(data=userData_df.to_numpy(), test_size=0.2, rating_threshold=4.0, exclude_unknowns=False, seed=123)
```

**Comment by yasdel** [comment]
Perfect, that solved the issue. I loaded the code into a server, and got this error:

```
Traceback (most recent call last):
  File "pandas/_libs/parsers.pyx", line 1119, in pandas._libs.parsers.TextReader._convert_tokens
  File "pandas/_libs/parsers.pyx", line 1244, in pandas._libs.parsers.TextReader._convert_with_dtype
  File "pandas/_libs/parsers.pyx", line 1259, in pandas._libs.parsers.TextReader._string_convert
  File "pandas/_libs/parsers.pyx", line 1450, in pandas._libs.parsers._string_box_utf8
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xba in position 10: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main_BookCrossing.py", line 54, in <module>
    userData_df = pd.read_csv(load_ds_addr, sep=';', skiprows=0)
  File "/home/yashar/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/yashar/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 460, in _read
    data = parser.read(nrows)
  File "/home/yashar/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 1198, in read
    ret = self._engine.read(nrows)
  File "/home/yashar/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 2157, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 847, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 862, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 941, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 1073, in pandas._libs.parsers.TextReader._convert_column_data
  File "pandas/_libs/parsers.pyx", line 1126, in pandas._libs.parsers.TextReader._convert_tokens
  File "pandas/_libs/parsers.pyx", line 1244, in pandas._libs.parsers.TextReader._convert_with_dtype
  File "pandas/_libs/parsers.pyx", line 1259, in pandas._libs.parsers.TextReader._string_convert
  File "pandas/_libs/parsers.pyx", line 1450, in pandas._libs.parsers._string_box_utf8
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xba in position 10: invalid start byte

```
May I ask your opinion if there is something specific with  BookCrossing dataset, that makes harder to work? The only difference I see with ML is that item IDs in BookCrossing are combination of integer and strings. In any case, some suggestion on how this issue could be resolved is very valuable. Thank you in advance.

**Comment by yasdel** [comment]
Thanks. That solved the issue. I received an error related to the decoding

`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xba in position 10: invalid start byte`

 which I addressed in the following way (added `encoding='unicode_escape')`

`userData_df = pd.read_csv(load_ds_addr, sep=';', encoding='unicode_escape', skiprows=0)
`
I am not sure if this is the best way. Regardless, I transferred the code to a server with excellent configurations (64VCPU and 256 GB RAM). I got the following result only for running MF:

```
/home/yashar/Softwares/cornac
   UserId      ItemId  Rating
0  276725  034545104X       0
1  276726  0155061224       5
2  276727  0446520802       0
3  276729  052165615X       3
4  276729  0521795028       6
(1149780, 3)
done

TEST:
...
   | NDCG@100 | Train (s) |  Test (s)
-- + -------- + --------- + ---------
MF |   0.0013 |    1.3669 | 1148.4577

```

There is something fishy going on here:

- Why test time takes much more than training? 
- Why test time is so high? (about 20 minutes)
- Finally, for this dataset, how can I change the threshold of positive ratings? (ratings are from 0-10).

It would be great if you could me troubleshoot this issue. Many thanks.

**Comment by tqtg** [comment]
The test time is high because you are using a ranking metric (NDCG@100), and there are many more items to be ranked in the Booking-Cross as compared to MovieLens-1M.

**Comment by yasdel** [comment]
thank you, that in fact was the reason.
