### ISSUE TITLE
[ASK]Getting Assertion Error During Hyper Parameter Tuning

### ISSUE THREAD

**Issue by LonePen** [PreferredAI/cornac#519]
### Description

I'm encountering an Assertion Error while attempting to perform hyperparameter optimization for my BPR model. Below is the code and error message. I would appreciate your assistance in resolving this issue.

`
import numpy as np
import cornac
from cornac.datasets import movielens
from cornac.eval_methods import RatioSplit
from cornac.hyperopt import Discrete, Continuous
from cornac.hyperopt import GridSearch, RandomSearch

import time

data_sales = list(zip(*map(train_data.get, train_data)))
rating_th = train_data.describe().iloc[-3]["rating"]

rs = RatioSplit(data=data_sales, test_size=0.2, rating_threshold=rating_th, seed=123)

rec100 = cornac.metrics.Recall(100)

bpr = cornac.models.BPR(k=100,max_iter = 200,learning_rate=0.05,lambda_reg=0.001,verbose=True,seed=42)

gs_bpr = GridSearch(
    model=bpr,
    space=[
        Discrete("max_iter", [20, 50, 100, 200]),
        Discrete("k", [10,20,50,100])
    ],
    metric=rec100,
    eval_method=rs,
)

cornac.Experiment(
    eval_method=rs,
    models=[gs_bpr],
    metrics=[rec100],
    user_based=False,
).run()

print('Grid search: ', gs_bpr.best_params)
`
`An error was encountered:

Traceback (most recent call last):
File "/data/hdfs4/yarn/local/usercache/Sajal.Garg/appcache/application_1681828537999_1825780/container_e53_1681828537999_1825780_01_000001/recomm_2.1.tar.gz/lib/python3.6/site-packages/cornac/experiment/experiment.py", line 130, in run
show_validation=self.show_validation,
File "/data/hdfs4/yarn/local/usercache/Sajal.Garg/appcache/application_1681828537999_1825780/container_e53_1681828537999_1825780_01_000001/recomm_2.1.tar.gz/lib/python3.6/site-packages/cornac/eval_methods/base_method.py", line 625, in evaluate
model.fit(self.train_set, self.val_set)
File "/data/hdfs4/yarn/local/usercache/Sajal.Garg/appcache/application_1681828537999_1825780/container_e53_1681828537999_1825780_01_000001/recomm_2.1.tar.gz/lib/python3.6/site-packages/cornac/hyperopt.py", line 131, in fit
assert val_set is not None
AssertionError`

**Comment by tqtg** [comment]
In order to do hyper-parameter search, you need a validation set. For `RatioSplit`, you can specify the `val_size` as similarly to `test_size`. You can also refer to [this tutorial](https://github.com/PreferredAI/cornac/blob/master/tutorials/param_search_vaecf.ipynb) as an example.
